<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CommonCrawler\Console\IndexController' => __DIR__ . '/src/CommonCrawler/Console/IndexController.php',
    'CommonCrawler\Controller\IndexController' => __DIR__ . '/src/CommonCrawler/Controller/IndexController.php',
    'CommonCrawler\Factory\Console\IndexFactory' => __DIR__ . '/src/CommonCrawler/Factory/Console/IndexFactory.php',
    'CommonCrawler\Factory\IndexFactory' => __DIR__ . '/src/CommonCrawler/Factory/IndexFactory.php',
    'CommonCrawler\Factory\IndexServiceFactory' => __DIR__ . '/src/CommonCrawler/Factory/IndexServiceFactory.php',
    'CommonCrawler\Factory\ZendDbSqlMapperFactory' => __DIR__ . '/src/CommonCrawler/Factory/ZendDbSqlMapperFactory.php',
    'CommonCrawler\Factory\ZendDbSqliteMapperFactory' => __DIR__ . '/src/CommonCrawler/Factory/ZendDbSqliteMapperFactory.php',
    'CommonCrawler\Mapper\IndexMapperInterface' => __DIR__ . '/src/CommonCrawler/Mapper/IndexMapperInterface.php',
    'CommonCrawler\Mapper\ZendDbSqlMapper' => __DIR__ . '/src/CommonCrawler/Mapper/ZendDbSqlMapper.php',
    'CommonCrawler\Mapper\ZendDbSqliteMapper' => __DIR__ . '/src/CommonCrawler/Mapper/ZendDbSqliteMapper.php',
    'CommonCrawler\Model\Index' => __DIR__ . '/src/CommonCrawler/Model/Index.php',
    'CommonCrawler\Model\IndexInterface' => __DIR__ . '/src/CommonCrawler/Model/IndexInterface.php',
    'CommonCrawler\PingController' => __DIR__ . '/src/CommonCrawler/Controller/PingController.php',
    'CommonCrawler\Service\IndexService' => __DIR__ . '/src/CommonCrawler/Service/IndexService.php',
    'CommonCrawler\Service\IndexServiceInterface' => __DIR__ . '/src/CommonCrawler/Service/IndexServiceInterface.php',
    'CommonCrawlerer\VersionController' => __DIR__ . '/src/CommonCrawler/Controller/VersionController.php',
);
