<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CommonCrawler\Mapper\IndexMapperInterface' => __DIR__ . '/Mapper/IndexMapperInterface.php',
    'CommonCrawler\Mapper\ZendDbSqliteMapper' => __DIR__ . '/Mapper/ZendDbSqliteMapper.php',
    'CommonCrawler\Mapper\ZendDbSqlMapper' => __DIR__ . '/Mapper/ZendDbSqlMapper.php',
    'CommonCrawler\PingController' => __DIR__ . '/Controller/PingController.php',
    'CommonCrawlerer\VersionController' => __DIR__ . '/Controller/VersionController.php',
    'CommonCrawler\Controller\IndexController' => __DIR__ . '/Controller/IndexController.php',
    'CommonCrawler\Model\Index' => __DIR__ . '/Model/Index.php',
    'CommonCrawler\Model\IndexInterface' => __DIR__ . '/Model/IndexInterface.php',
    'CommonCrawler\Service\IndexService' => __DIR__ . '/Service/IndexService.php',
    'CommonCrawler\Service\IndexServiceInterface' => __DIR__ . '/Service/IndexServiceInterface.php',
    'CommonCrawler\Factory\ZendDbSqlMapperFactory' => __DIR__ . '/Factory/ZendDbSqlMapperFactory.php',
    'CommonCrawler\Factory\IndexFactory' => __DIR__ . '/Factory/IndexFactory.php',
    'CommonCrawler\Factory\ZendDbSqliteMapperFactory' => __DIR__ . '/Factory/ZendDbSqliteMapperFactory.php',
    'CommonCrawler\Factory\Console\IndexFactory' => __DIR__ . '/Factory/Console/IndexFactory.php',
    'CommonCrawler\Factory\IndexServiceFactory' => __DIR__ . '/Factory/IndexServiceFactory.php',
    'CommonCrawler\Console\IndexController' => __DIR__ . '/Console/IndexController.php',
);
